### PR TITLE
libgeotiff 1.4.3 plus shared library building patches

### PR DESCRIPTION
**Pull request by hobu**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hobu** [comment]
@gillins @ocefpaf This should be good now

**Comment by gillins** [comment]
@ocefpaf Should there be a pinning for `geotiff`? I can't find one...

**Comment by hobu** [comment]
The changelog for 1.4.3 is rather minimal https://lists.osgeo.org/pipermail/geotiff/2018-December/000846.html

**Comment by ocefpaf** [comment]
> @ocefpaf Should there be a pinning for `geotiff`? I can't find one...

We probably should pin it in https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml

It looks like we can pin to x.x  starting from 1.4.1:

https://abi-laboratory.pro/?view=timeline&l=libgeotiff

I'll send the PR and we can add `run_exports` here too.

**Comment by ocefpaf** [comment]
Thanks @hobu!

**Pull request merged**
